"""Canonical Pydantic models shared across agents."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------- job models


class JobPosting(BaseModel):
    """A raw job posting from any board."""

    job_id: str
    title: str
    company: str
    location: str = ""
    board: str = ""
    url: str = ""
    description: str = ""
    date_posted: Optional[datetime] = None
    is_remote: bool = False
    salary_min: Optional[int] = None
    salary_max: Optional[int] = None


class JobAnalysis(BaseModel):
    """Structured signals extracted from a job description."""

    job_id: str
    title: str = ""
    company: str = ""

    required_skills: list[str] = Field(default_factory=list)
    preferred_skills: list[str] = Field(default_factory=list)
    seniority_level: str = "mid"  # junior | mid | senior | staff
    years_experience: int = 0
    must_have_keywords: list[str] = Field(default_factory=list)
    company_values: list[str] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)
    remote_policy: str = "unspecified"
    salary_range: Optional[tuple[int, int]] = None

    # Provenance: "llm" or "heuristic" (fallback when no API key configured)
    extractor: str = "heuristic"


class ScoredJob(BaseModel):
    """A job with an attached fit score."""

    job: JobPosting
    analysis: Optional[JobAnalysis] = None
    fit_score: float = 0.0
    score_breakdown: dict[str, Any] = Field(default_factory=dict)
    passed_filter: bool = False
    reject_reason: str = ""


# ------------------------------------------------------------ resume models


class Bullet(BaseModel):
    """One experience bullet from the base resume."""

    id: str
    text: str
    skills: list[str] = Field(default_factory=list)
    company: str = ""
    role: str = ""


class ResumeDocument(BaseModel):
    """Parsed base resume — the source of truth for facts."""

    name: str = ""
    email: str = ""
    phone: str = ""
    summary: str = ""
    skills: list[str] = Field(default_factory=list)
    bullets: list[Bullet] = Field(default_factory=list)
    seniority: str = "mid"
    years_experience: int = 0
    raw_text: str = ""


class TailoredResume(BaseModel):
    """A job-specific resume variant generated by the tailor."""

    job_id: str
    text: str = ""
    markdown: str = ""
    source_bullets: list[str] = Field(default_factory=list)
    guardrail_violations: list[str] = Field(default_factory=list)
    validated: bool = False
    model_used: str = ""


class CoverLetter(BaseModel):
    """A role-specific cover letter."""

    job_id: str
    text: str = ""
    word_count: int = 0
    model_used: str = ""


# ------------------------------------------------------- application models


APPLICABLE_STATUSES = (
    "draft",
    "pending_review",
    "approved",
    "rejected_by_user",
    "submitted",
    "no_response",
    "rejected",
    "phone_screen",
    "interview",
    "offer",
    "declined",
)


class ApplicationRecord(BaseModel):
    """One tracked application row."""

    id: Optional[int] = None
    job_id: str
    title: str = ""
    company: str = ""
    board: str = ""
    url: str = ""
    applied_at: Optional[datetime] = None
    status: str = "draft"
    fit_score: float = 0.0
    ats_score_before: Optional[float] = None
    ats_score_after: Optional[float] = None
    resume_variant_hash: str = ""
    coverletter_hash: str = ""
    tailored_resume_path: str = ""
    coverletter_path: str = ""
    notes: str = ""
    variant: str = "A"               # A/B testing: which style guide version
    outcome_source: str = ""         # 'email_triage' | 'manual_update' | ...


class HumanDecision(BaseModel):
    """The human review verdict for one tailored application."""

    job_id: str
    decision: str  # approve | reject | skip
    notes: str = ""
    decided_at: datetime = Field(default_factory=datetime.utcnow)


class LLMResponse(BaseModel):
    """Normalized response from any provider in the chain."""

    text: str
    model: str
    provider: str
